name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build and test with Maven
        run: mvn -B clean verify --file ./simple-api/pom.xml

      - name: Afficher l'identifiant DockerHub (test)
        run: |
          echo "Nom d'utilisateur DockerHub : ${{ secrets.DOCKERHUB_USERNAME }}"
