name: Deploy Docker App

on:
  push:
    branches:
      - main # Déploie uniquement quand on pousse sur le main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t nassim77/tp-devops-simple-api:latest ./simple-api

      - name: Push Docker image to Hub
        run: docker push nassim77/tp-devops-simple-api:latest

      - name: Deploy app on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 4.231.234.236
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker pull nassim77/tp-devops-simple-api:latest
            docker stop backend-api || true
            docker rm backend-api || true
            docker run -d --name backend-api -p 8080:8080 nassim77/tp-devops-simple-api:latest
